export const siteContent = {
  creator: {
    name: "Deniz Ünlü",
    eyebrow: "METİN2 YAYINCISI & İÇERİK ÜRETİCİSİ",
    headline: "Yayın kaçarsa, arşiv burada.",
    description:
      "Canlı yayınlar, güncel Metin2 videoları, topluluk bağlantıları ve Deniz Ünlü arşivi tek merkezde.",
  },
  links: {
    live: "",
    youtube: "https://www.youtube.com/@Deniz%C3%9Cnl%C3%BC-PVP10",
    whatsapp: "https://www.whatsapp.com/channel/0029VbBlxLe1NCrap6dyzW3L",
    kick: "https://kick.com/denizunlupvp/about",
    tiktok: "",
    discord: "https://discord.gg/bVzxKr7yaj",
    dailymotion: "https://www.dailymotion.com/user/denizunlu",
  },
  platforms: [
    {
      key: "youtube",
      short: "YT",
      name: "YouTube",
      description: "Güncel videolar",
      tone: "red",
      available: true,
    },
    {
      key: "kick",
      short: "K",
      name: "Kick",
      description: "Canlı yayın",
      tone: "green",
      available: true,
    },
    {
      key: "tiktok",
      short: "TT",
      name: "TikTok",
      description: "Kısa videolar",
      tone: "pink",
      available: false,
    },
    {
      key: "discord",
      short: "DC",
      name: "Discord",
      description: "Topluluk",
      tone: "purple",
      available: true,
    },
    {
      key: "whatsapp",
      short: "WA",
      name: "WhatsApp",
      description: "Anlık duyurular",
      tone: "emerald",
      available: true,
    },
  ],
  videos: [
    {
      id: "v1",
      videoId: "zJD9KLZ2rJk",
      index: "01",
      tag: "GÜNCEL VİDEO",
      title:
        "6 aylık emek ve sonunda başardık: +15 Yılan Zırhı! +25.000 Won | Metin2 - Rohan2",
      duration: "15:50",
      accent: "blue",
      thumbnailUrl: "https://i.ytimg.com/vi/zJD9KLZ2rJk/hqdefault.jpg",
      href: "/videolar/zJD9KLZ2rJk",
    },
    {
      id: "v2",
      videoId: "DsfcioiTcoE",
      index: "02",
      tag: "GÜNCEL VİDEO",
      title:
        "Kuzey2 item kopyalama hilesi gibi 2 eşya! Serverin en iyi farmlık ayakkabısı",
      duration: "14:48",
      accent: "gold",
      thumbnailUrl: "https://i.ytimg.com/vi/DsfcioiTcoE/hqdefault.jpg",
      href: "/videolar/DsfcioiTcoE",
    },
    {
      id: "v3",
      videoId: "gyhUGE3BYCU",
      index: "03",
      tag: "GÜNCEL VİDEO",
      title:
        "Kuzey2 her tıklama +5.000 TL! Gidişatı değiştiren +9 elit deneme",
      duration: "21:02",
      accent: "cyan",
      thumbnailUrl: "https://i.ytimg.com/vi/gyhUGE3BYCU/hqdefault.jpg",
      href: "/videolar/gyhUGE3BYCU",
    },
    {
      id: "v4",
      videoId: "xbltCeNb8sI",
      index: "04",
      tag: "GÜNCEL VİDEO",
      title:
        "Kuzey2 52 ort KDP ile haritaları yok ediyor — 6 saniyede 1 Metin Taşı",
      duration: "19:24",
      accent: "gold",
      thumbnailUrl: "https://i.ytimg.com/vi/xbltCeNb8sI/hqdefault.jpg",
      href: "/videolar/xbltCeNb8sI",
    },
  ],
  archiveVideos: [
    {
      id: "archive-1",
      videoId: "zJD9KLZ2rJk",
      title:
        "6 aylık emek ve sonunda başardık: +15 Yılan Zırhı! +25.000 Won | Metin2 - Rohan2",
      description: "Aktif YouTube kanalındaki güncel Metin2 videosu.",
      category: "guncel",
      categoryLabel: "Güncel",
      source: "YouTube",
      status: "Yayında",
      duration: "15:50",
      year: "2026",
      accent: "blue",
      thumbnailUrl: "https://i.ytimg.com/vi/zJD9KLZ2rJk/hqdefault.jpg",
      href: "/videolar/zJD9KLZ2rJk",
    },
    {
      id: "archive-2",
      videoId: "DsfcioiTcoE",
      title:
        "Kuzey2 item kopyalama hilesi gibi 2 eşya! Serverin en iyi farmlık ayakkabısı",
      description: "Aktif YouTube kanalındaki güncel Metin2 videosu.",
      category: "guncel",
      categoryLabel: "Güncel",
      source: "YouTube",
      status: "Yayında",
      duration: "14:48",
      year: "2026",
      accent: "gold",
      thumbnailUrl: "https://i.ytimg.com/vi/DsfcioiTcoE/hqdefault.jpg",
      href: "/videolar/DsfcioiTcoE",
    },
    {
      id: "archive-3",
      videoId: "gyhUGE3BYCU",
      title:
        "Kuzey2 her tıklama +5.000 TL! Gidişatı değiştiren +9 elit deneme",
      description: "Aktif YouTube kanalındaki güncel Metin2 videosu.",
      category: "guncel",
      categoryLabel: "Güncel",
      source: "YouTube",
      status: "Yayında",
      duration: "21:02",
      year: "2026",
      accent: "cyan",
      thumbnailUrl: "https://i.ytimg.com/vi/gyhUGE3BYCU/hqdefault.jpg",
      href: "/videolar/gyhUGE3BYCU",
    },
    {
      id: "archive-4",
      videoId: "xbltCeNb8sI",
      title:
        "Kuzey2 52 ort KDP ile haritaları yok ediyor — 6 saniyede 1 Metin Taşı",
      description: "Aktif YouTube kanalındaki güncel Metin2 videosu.",
      category: "guncel",
      categoryLabel: "Güncel",
      source: "YouTube",
      status: "Yayında",
      duration: "19:24",
      year: "2026",
      accent: "gold",
      thumbnailUrl: "https://i.ytimg.com/vi/xbltCeNb8sI/hqdefault.jpg",
      href: "/videolar/xbltCeNb8sI",
    },
  ],
  servers: [
    {
      name: "Kuzey2",
      code: "K2",
      status: "AKTİF",
      detail: "Deniz Ünlü'nün aktif olarak oynadığı Metin2 PvP sunucusu.",
      url: "https://kuzey2.com/",
      isVisible: true,
    },
    {
      name: "Rohan2",
      code: "R2",
      status: "AKTİF",
      detail: "Deniz Ünlü'nün aktif olarak oynadığı Metin2 PvP sunucusu.",
      url: "https://rohan2.com.tr/?lang=tr",
      isVisible: true,
    },
  ],
} as const;
